# .
# ├── Jenkinsfile
# ├── VERSION              # file with current semver, e.g., 1.2.3
# ├── Dockerfile
# └── cloudbuild.yaml


# Cloud Build configuration for semantic versioning

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:$TAG_NAME', '.']

images:
  - 'gcr.io/$PROJECT_ID/my-app:$TAG_NAME'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-app', '--image', 'gcr.io/$PROJECT_ID/my-app:$TAG_NAME', '--platform', 'managed', '--region', 'us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'update-traffic', 'my-app', '--to-latest', '--platform', 'managed', '--region', 'us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'delete', 'my-app', '--platform', 'managed', '--region', 'us-central1', '--quiet']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'list', '--platform', 'managed', '--region', 'us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'describe', 'my-app', '--platform', 'managed', '--region', 'us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'logs', 'my-app', '--platform', 'managed', '--region', 'us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'update', 'my-app', '--image', 'gcr.io/$PROJECT_ID/my-app:$TAG_NAME', '--platform', 'managed', '--region', 'us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'set-traffic', 'my-app', '--to-latest', '--platform', 'managed', '--region', 'us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'logs', 'my-app', '--platform', 'managed', '--region', 'us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'update-traffic', 'my-app', '--to-latest', '--platform', 'managed', '--region', 'us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'delete', 'my-app', '--platform', 'managed', '--region', 'us-central1', '--quiet']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'services', 'list', '--platform', 'managed', '--region', 'us-central1']



    