# cloudbuild-basic.yaml
steps:
  # Step 1: Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA', '.']

  # Step 2: Push image to Container Registry / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'flask-app',
        '--image', 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA',
        '--region', '$REGION',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA'
timeout: '1200s'  # 20 minutes